version: "3"

services:
  postgres:
    image: postgres:10.5-alpine
    environment:
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST}:${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME}:${PGDATA}
