version: "3"

services:
  postgres:
    image: postgres:10.5-alpine
    environment:
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:${POSTGRES_OUTER_PORT}:5432
    volumes:
      - ./_data/postgres:${PGDATA}